// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjKaDa3IusnpiKGNc_qkUgOjF5rPUtOmI',
    appId: '1:880619278696:web:f8b162472c3dd27c1946dd',
    messagingSenderId: '880619278696',
    projectId: 'products-64ead',
    authDomain: 'products-64ead.firebaseapp.com',
    storageBucket: 'products-64ead.appspot.com',
    measurementId: 'G-XEZ7TP7QHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDigiPo2dNSd4sOJC756pbmIVrpcWR0g_8',
    appId: '1:880619278696:android:453afb0f25d2c71a1946dd',
    messagingSenderId: '880619278696',
    projectId: 'products-64ead',
    storageBucket: 'products-64ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbVzuF4Pa1d_xJgU8YbwF-2Iezz7UNOZU',
    appId: '1:880619278696:ios:6242a6893f4a65b71946dd',
    messagingSenderId: '880619278696',
    projectId: 'products-64ead',
    storageBucket: 'products-64ead.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbVzuF4Pa1d_xJgU8YbwF-2Iezz7UNOZU',
    appId: '1:880619278696:ios:6242a6893f4a65b71946dd',
    messagingSenderId: '880619278696',
    projectId: 'products-64ead',
    storageBucket: 'products-64ead.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjKaDa3IusnpiKGNc_qkUgOjF5rPUtOmI',
    appId: '1:880619278696:web:cf183ae8c838a7c41946dd',
    messagingSenderId: '880619278696',
    projectId: 'products-64ead',
    authDomain: 'products-64ead.firebaseapp.com',
    storageBucket: 'products-64ead.appspot.com',
    measurementId: 'G-R3VYE7W3SV',
  );

}